      SUBROUTINE RKGS(PRMT,Y,DERY,NDIM,IHLF,AUX,DELT2)

      include "COMMON.f"

C**********************************************************************
C    USING A FOURTH ORDER RUNGE-KUTTA FORMULA WITH GILL MODIFICATION  *
C    TO SOLVE A SYSTEM OF FIRST ORDER ORDINARY DIFFERENTIAL EQUATIONS *
C    WITH GIVEN INITIAL VALUES.                                       *
C**********************************************************************
C      INTEGER*2 NLIN1,NLIN2,NODE1,IWAVE,NP,FS,S,ITHR,IPRNT, pltn 
C      DIMENSION Y(5100),DERY(5100),AUX(8,5100),PRMT(5),A(4),B(4),C(4)
C      COMMON F,R,T,SODO,SODI,POTO,POTI,PNAB,PKB,PPB,GL,VL,ER
C      COMMON VMAX,VTH,IPT,IPRNT,NLIN1,NLIN2,NON,XPD,XPD2,UIO,UIO2
C      COMMON NODE,NODE1
C      COMMON IWAVE,FREQ,FREQ2,AMP2,ANGLE,ANGLE2,DCOFF,TAUS,DELAY
C      COMMON PROD,PROD2,XMULT,PIMULT
C      COMMON CA(4,3),CB(4,3),CGA,CGM,CCM,AREA,XA,YA,XC,YC,WIREL,EL,RHOE
C      COMMON TIM(1100),EPOT(1100),EPT(1100)
C      COMMON UINA(1100),UIK(1100),UIP(1100),UIL(1100)
C      COMMON TMAX,TEND,ITHR,INNGTT,NNGTT,NODEZ
C      COMMON/SWTCH/FS,S,pltn,TT,tflag(6),Tp,nfound
C      COMMON/FLD/VREF,DIAM,NP,PL(128),PT(128)
C      COMMON/CBPARM/AB,LBH,CMB,GMB !AREA,RESISTANCE,CAPACITANCE,CONDUCTANCE CELL BODY
C      COMMON/HPARAM/AH,LHN,CMH,GMH !AREA,RESISTANCE,CAPACITANCE,CONDUCTANCE HILLOCK
C      COMMON/WPARM/WB,DIAMB,WH,DIAMH,AN,GAP,GAH,GAB,SUMK(1100)
      DIMENSION A(4),B(4),C(4)
      INIT=0
      DO 1 I = 1,NDIM
        AUX(8,I)=.06666667*DERY(I)
    1 CONTINUE
      X=PRMT(1)
      XEND=PRMT(2)
      H=PRMT(3)
      PRMT(5)=0.0

      CALL FCT(X,Y,DERY,PRMT)

C     ERROR TEST
      IF(H*(XEND-X))38,37,2
C     PREPARATION FOR RUNGE-KUTTA METHOD
    2 A(1)=.5
      A(2)=.2928932
      A(3)=1.707107
      A(4)=.1666667
      B(1)=2.
      B(2)=1.
      B(3)=1.
      B(4)=2.
      C(1)=.5
      C(2)=.2928932
      C(3)=1.707107
      C(4)=.5
C     PREPARATION OF FIRST RUNGE-KUTTA STEP
      DO 3 I=1,NDIM
        AUX(1,I)=Y(I)
        AUX(2,I)=DERY(I)
        AUX(3,I)=0.0
        AUX(6,I)=0.0
    3 CONTINUE
      IREC=0
      H=H+H
      IHLF=-1
      ISTEP=0
      IEND=0
C     START OF A RUNGE-KUTTA STEP
    4 IF((X+H-XEND)*H)7,6,5
    5 H=XEND-X
    6 IEND=1
C     RECORDING OF INITIAL VALUES OF THE STEP

    7 CALL OUTP(X,Y,DERY,IREC,NDIM,PRMT)

      IF(PRMT(5)) 40,8,40
    8 ITEST=0
    9 ISTEP=ISTEP+1
C     START OF INNERMOST RUNGE-KUTTA LOOP
      J=1
   10 AJ=A(J)
      BJ=B(J)
      CJ=C(J)
      DO 11 I = 1,NDIM
        R1=H*DERY(I)
        R2=AJ*(R1-BJ*AUX(6,I))
        Y(I)=Y(I)+R2
        R2=R2+R2+R2
        AUX(6,I)=AUX(6,I)+R2-CJ*R1
C      IF(I.EQ.19)WRITE(66,*)'TIM(19)= ',TIM(19),' R1= ',R1 !DIAGNOSTIC 
   11 CONTINUE
      IF (J-4) 12,15,15
   12 J=J+1
      IF(J-3) 13,14,13
   13 X=X+.5*H

   14 CALL FCT(X,Y,DERY,PRMT)

      GO TO 10
C     END OF INNERMOST RUNGE-KUTTA LOOP

C     TEST OF ACCURACY

15    IF(ITEST)16,16,20
C     IN CASE ITEST=0 THERE IS NO POSSIBILITY FOR TESTING OF ACCURACY
   16 DO 17 I=1,NDIM
        AUX(4,I)=Y(I)
   17 CONTINUE
      ITEST = 1
      ISTEP=ISTEP+ISTEP-2
   18 IHLF=IHLF+1
      X=X-H
      H=.5*H
      DO 19 I=1,NDIM
        Y(I)=AUX(1,I)
        DERY(I)=AUX(2,I)
        AUX(6,I)=AUX(3,I)
   19 CONTINUE
      GO TO 9
C     IN CASE ITEST=1 TESTING OF ACCURACY IS POSSIBLE
20    IMOD=ISTEP/2
      IF(ISTEP-IMOD-IMOD) 21,23,21

   21 CALL FCT(X,Y,DERY,PRMT)

      DO 22 I=1,NDIM
        AUX(5,I)=Y(I)
        AUX(7,I)=DERY(I)
   22 CONTINUE
      GO TO 9
C     COMPUTATION OF TEST VALUE DELT
   23 DELT=0.
      DO 24 I=1,NDIM
        DELT=DELT+AUX(8,I)*ABS(AUX(4,I)-Y(I))
   24 CONTINUE
      IF (DELT-PRMT(4)) 28,28,25
C     ERROR IS TOO GREAT
   25 IF(IHLF-10) 26,36,36
   26 DO 27 I=1,NDIM
        AUX(4,I)=AUX(5,I)
   27 CONTINUE
      ISTEP=ISTEP+ISTEP-4
      X=X-H
      IEND=0

      GO TO 18
C     RESULT VALUES ARE GOOD

   28 CALL FCT(X,Y,DERY,PRMT)

      DO 29 I=1,NDIM
        AUX(1,I)=Y(I)
        AUX(2,I)=DERY(I)
        AUX(3,I)=AUX(6,I)
        Y(I)=AUX(5,I)
        DERY(I)=AUX(7,I)
   29 CONTINUE
      IF(INIT .EQ. 0)THEN
        HSAV=H
        INIT=1
      ENDIF
      IF(DELT2 .EQ. 0.0)DELT2=H

      CALL OUTP(X-H,Y,DERY,IHLF,NDIM,PRMT)

      IF(IWAVE.NE.15)THEN  !! 11/12/03, 6 changed to 15: Check out.
        IF(X .GT. PT(NP))THEN
          H=DELT2
          GOTO 307
        ENDIF
        DO LL = 1,NP
          IF(X .GE. PL(LL) .AND. X .LE. PT(np))THEN
            H=HSAV
            GOTO 306
          ELSE
            H=DELT2
          ENDIF   ! GE PL(LL) AND LE PT(LL)
        ENDDO   !NP
      ENDIF   !IWAVE
306   CONTINUE
307   CONTINUE
      IF (PRMT(5)) 40,30,40
   30 DO 31 I=1,NDIM
        Y(I)=AUX(1,I)
        DERY(I)=AUX(2,I)
   31 CONTINUE
      IREC=IHLF
      IF(IEND) 32,32,39
C     INCREMENT GETS DOUBLED
   32 IHLF=IHLF-1
      ISTEP=ISTEP/2
      H=H+H
      IF(IHLF)4,33,33
   33 IMOD=ISTEP/2
      IF(ISTEP-IMOD-IMOD)4,34,4
   34 IF(DELT-.02*PRMT(4))35,35,4
   35 IHLF=IHLF-1
      ISTEP=ISTEP/2
      H=H+H
      GO TO 4
C     RETURNS TO CALLING PROGRAM
   36 IHLF=11

      CALL FCT(X,Y,DERY,PRMT)

      GO TO 39
   37 IHLF=12
      GO TO 39
   38 IHLF=13

   39 CALL OUTP(X,Y,DERY,IHLF,NDIM,PRMT)

   40 RETURN
      END
